### ISSUE TITLE
Exclude pattern is not make effect when setting in ~/.rubocop.yml for emacs flycheck.

### ISSUE THREAD

**Issue by zw963** [flycheck/flycheck#1368]
Please see follow links, thanks

https://github.com/bbatsov/rubocop/issues/5139#issuecomment-348678866

**Comment by cpitclaudel** [comment]
Thanks. Would you like to submit a pull request?

**Comment by zw963** [comment]
Sorry, I think this feature is added in newest version flycheck.

Thanks very much.

**Comment by zw963** [comment]
Hi, I think something still borken this feature.

when I run follow command, rubocop check is skipped as expect.
```sh
rubocop --display-cop-names --force-exclusion --format emacs --cache false --config ~/.rubocop.yml db/schema.rb
```

But, when I open db/schema.rb with a opened emacs frame, rubocop check is still invoked.
and told me following error:

```sh
Warning (flycheck): Syntax checker ruby-rubocop reported too many errors (4929) and is disabled.
Warning (flycheck): Syntax checker ruby-rubocop reported too many errors (4929) and is disabled.
```

**Comment by zw963** [comment]
I think, flycheck just not try to mark current buffer to show warning message, but, rubocop is run
against excluded file, my db/schema.rb is a big file, so, mostly, when i open this file, CPU usage
is very high.

**Comment by fmdkdd** [comment]
Hmm, what happens if you run:

```
rubocop --display-cop-names --force-exclusion --format emacs --cache false --config ~/.rubocop.yml schema.rb
```

That is, when you run `robocop` directly from the `db` folder?  Is the file `db/schema.rb` excluded, or does `rubocop` see it?

**Comment by zw963** [comment]
@fmdkdd , sorry, the correct command is:

```sh
rubocop --display-cop-names --force-exclusion --format emacs --cache false --config ~/.rubocop.yml db/schema.rb
```
~/.rubocop.yml config like this:

```yaml
AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
  - 'vendor/**/*'
  - 'spec/fixtures/**/*'
  - 'db/schema.rb'
  - 'db/migrate/*'
  - 'bin/bundle'
  - 'bin/rails'
  - 'bin/rake'
  - 'bin/setup'
  - 'bin/spring'
  - 'config/**/*'
  - 'script/**/*'
  - !ruby/regexp /old_and_unused\.rb$/

  TargetRubyVersion:
    2.3
```

But, if run with `.... schema.rb` as prevoius reply, `--force-exclusion` is not work.
